#########################################
# AFK DETECTION by lolmayaaa
# Test line 1
# Version: 1.0 (Legacy)
#########################################

# How many seconds of not moving is going to alert the player? For example: 60
afktimer: 60

# What should be the reason for the kick?
reason: 'Stop being AFK!'

# Should it announce what player was kicked for being afk?
announce: true

# Warning intervals (in seconds)
warnings: [30, 15, 5, 4, 3, 2, 1]